In [1]:
import pandas as pd
import uuid
df = pd.read_csv('books.csv')

In [2]:
df1 = pd.DataFrame(columns=['author', 'authorId'])
df2 = pd.DataFrame(columns=['authorId', 'isbn'])

In [3]:
for index, row in df.iterrows():
    authors = row['authors'].split(',')
    for author in authors:
        tempdf = pd.DataFrame()
        newRow = {'author' : author}
        new_data = pd.DataFrame([newRow])
        df1 = pd.concat([df1, new_data], ignore_index = True)
        df1 = df1.drop_duplicates()

In [4]:
df1['authorId'] = [uuid.uuid4() for _ in range(len(df1.index))]

In [5]:
display(df1)

                 author                              authorId
0       Suzanne Collins  f60842d3-be8c-45d7-89cd-3efd7d14872b
1          J.K. Rowling  15b85a59-0288-47c7-a6ff-8e4ebd29a042
2         Mary GrandPré  f506529e-653b-4d10-bcc2-08233e31fd18
3       Stephenie Meyer  38b2850c-37fd-44d8-b0f7-b18cc0233195
4            Harper Lee  d11963c4-d7e2-4396-a8d9-9938ba08222c
...                 ...                                   ...
5813        Lisa Tuttle  ffa25ffa-b35a-490b-b3c6-8c047b5bf33b
5814      Connie Willis  42fd26ae-bfb2-4c0e-82a7-afc986f573d7
5815   Patrick Rothfuss  e139f321-d1aa-4dc4-8bed-434964d0dec0
5816       Jodi Daynard  055b5b8f-7414-47fd-a027-aeb32f459ece
5817        Cora Reilly  4ca50fc8-52e8-4a6f-8e88-7c4ef428683b

[5818 rows x 2 columns]

In [6]:
for index, row in df.iterrows():
    authors = row['authors'].split(',')
    isbn = row['isbn13']
    for author in authors:
        tempdf = pd.DataFrame()
        tempdf = df1[df1['author'].isin([author])]
        authorId = tempdf['authorId'].to_string()
        authorId = authorId.split()[1]
        newRow = {'authorId': authorId, 'isbn': isbn }
        new_row = pd.DataFrame([newRow])
        df2 = pd.concat([df2, new_row], ignore_index = True)

In [7]:
display(df2)

                                   authorId           isbn
0      f60842d3-be8c-45d7-89cd-3efd7d14872b  9780439023480
1      15b85a59-0288-47c7-a6ff-8e4ebd29a042  9780439554930
2      f506529e-653b-4d10-bcc2-08233e31fd18  9780439554930
3      38b2850c-37fd-44d8-b0f7-b18cc0233195  9780316015840
4      d11963c4-d7e2-4396-a8d9-9938ba08222c  9780061120080
...                                     ...            ...
12456  055b5b8f-7414-47fd-a027-aeb32f459ece  9780441019460
12457  4ca50fc8-52e8-4a6f-8e88-7c4ef428683b  9780679733710
12458  ecb89df9-0ec2-484c-bc18-cde0ff3bc3c9  9780393307630
12459  51c59af5-c8d9-4df8-b506-3c0f9c23f364  9780061711530
12460  9065819c-c48a-44c2-b9a2-b2f1074bde36  9780375700450

[12461 rows x 2 columns]

In [9]:
df1.to_csv('Author.csv', index=False)
df2.to_csv('BookAuthor.csv', index=False)